version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aipassword
      POSTGRES_DB: ai_interviewer
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://aiuser:aipassword@db:5432/ai_interviewer
      # Add other backend env vars here
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
      # Add other frontend env vars here
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata: 