services:
  - type: web
    name: ai-interviewer-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python db/create_tables.py && python -m uvicorn api.main:app --host 0.0.0.0 --port 8000
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-interviewer-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /

  - type: web
    name: ai-interviewer-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://ai-interviewer-backend.onrender.com # Update this after first deploy with your backend's Render URL
    autoDeploy: true

databases:
  - name: ai-interviewer-db
    plan: free
    databaseName: ai_interviewer
    user: ai_interviewer_user
